# Generated by Django 4.1.2 on 2023-01-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_post_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='In progress', verbose_name='text'),
        ),
    ]
