# Generated by Django 4.1.2 on 2023-01-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment_text_en_us_comment_text_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(default='', null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(default='', null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='...'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_en_us',
            field=models.TextField(default='...', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_ru',
            field=models.TextField(default='...', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='', verbose_name='text'),
        ),
    ]
