# Generated by Django 4.1.2 on 2023-01-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_post_text_en_us_post_text_ru_post_title_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='In progress', verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(default='In progress', null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_ru',
            field=models.TextField(default='In progress', null=True, verbose_name='text'),
        ),
    ]
